services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: reallyStrongRootPWD!
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolioUser
      MYSQL_PASSWORD: reallyStrongPWD!
    ports:
      - "3306:3306"
    volumes:
      - portfolioData:/var/lib/mysql

  # Go application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    volumes:
      - .:/app
    command: ["air"]
    depends_on:
      - mysql
      - qdrant
    ports:
      - "6001:6001"

  # Qdrant Service
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data_volume:/qdrant/storage
    configs:
      - source: qdrant_config
configs:
  qdrant_config:
    content: |
      log_level: INFO
volumes:
  portfolioData:
  qdrant_data_volume:
