name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_PORTFOLIO }}
          password: ${{ secrets.DOCKER_PASSWORD_PORTFOLIO }}
          registry: reg.paul-wortmann.me

      - name: Create .env file
        run: | 
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_CHARSET=${{ secrets.CHARSET }}" >> .env
          echo "DB_CORS_ORIGIN0=${{ secrets.CORS_ORIGIN0 }}" >> .env
          echo "DB_CORS_ORIGIN1=${{ secrets.CORS_ORIGIN1 }}" >> .env
          

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: reg.paul-wortmann.me/portfolio_api/portfolio_api:latest
