name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_PORTFOLIO }}
          password: ${{ secrets.DOCKER_PASSWORD_PORTFOLIO }}
          registry: reg.paul-wortmann.me

      - name: Create .env file
        run: | 
          echo "CORS_ORIGIN0=${{ secrets.CORS_ORIGIN0 }}" >> .env
          echo "CORS_ORIGIN1=${{ secrets.CORS_ORIGIN1 }}" >> .env
          echo "GIN_MODE=${{ secrets.GIN_MODE }}" >> .env
          echo "DB_DSN=${{ secrets.DB_DSN }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "API_ENDPOINT_URL=${{ secrets.API_ENDPOINT_URL }}" >> .env
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            reg.paul-wortmann.me/portfolio_api/portfolio_api:latest
            reg.paul-wortmann.me/portfolio_api/portfolio_api:${{ github.sha }}
